-- ============================================================================
--  DevNet - Red Social para Desarrolladores
--  V1__baseline.sql : modelo fisico inicial (Sprint 1)
--
--  Motor    : PostgreSQL 15 o superior (Supabase)
--  Gestion  : Flyway. Esta carpeta es la UNICA fuente de verdad del esquema.
--             Hibernate corre siempre con ddl-auto=validate (ADR-003).
--  Modelo   : docs/bd/02-modelo-logico.md
--  Consultas: docs/bd/01-consultas-clave.md
--
--  CONVENCIONES
--    * snake_case, identificadores en espanol y sin acentos.
--    * Claves primarias uuid generadas por la base con gen_random_uuid()
--      (nucleo de PostgreSQL desde la version 13; no requiere extension).
--    * Toda marca de tiempo es timestamptz almacenada en UTC.
--    * Los estados se modelan como text + CHECK y no como ENUM nativo,
--      por compatibilidad con @Enumerated(EnumType.STRING) de JPA.
--    * Sin ON DELETE CASCADE sobre contenido con valor historico: se usa
--      desactivacion de cuenta y borrado logico para preservar trazabilidad.
--      CASCADE se reserva a dependencias estructurales puras.
--
--  FUERA DE ALCANCE DE ESTA MIGRACION
--    Roles de base de datos y privilegios -> docs/bd/db-roles.sql
--      (aprovisionamiento del entorno, se ejecuta una vez por proyecto).
--    Triggers de auditoria y de contadores  -> V3 (Sprint 3).
--    sp_consolidar_metricas_diarias          -> V3 (Sprint 3).
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 0. Funcion comun de marca de actualizacion
-- ----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION fn_set_actualizado_en()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.actualizado_en := now();
    RETURN NEW;
END;
$$;

COMMENT ON FUNCTION fn_set_actualizado_en() IS
    'Mantiene actualizado_en. Es mantenimiento de metadatos, no logica de negocio (lineamientos 5.4).';


-- ============================================================================
-- 1. IDENTIDAD Y ACCESO   (modulo transversal - lineamientos 3.1)
-- ============================================================================

CREATE TABLE rol (
    id          smallint     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      text         NOT NULL UNIQUE,
    descripcion text         NOT NULL,
    exige_mfa   boolean      NOT NULL DEFAULT false,
    CONSTRAINT ck_rol_codigo
        CHECK (codigo IN ('VISITANTE', 'DESARROLLADOR', 'MODERADOR', 'ADMIN'))
);

COMMENT ON COLUMN rol.exige_mfa IS
    'Convierte "este rol exige segundo factor" en dato y no en condicional del codigo (ADR-004).';


CREATE TABLE permiso (
    id          smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      text     NOT NULL UNIQUE,
    descripcion text     NOT NULL
);

COMMENT ON TABLE permiso IS
    'La autorizacion evalua permisos, no nombres de rol: cambiar lo que puede hacer un rol es una fila, no un despliegue.';


CREATE TABLE rol_permiso (
    rol_id     smallint NOT NULL REFERENCES rol(id)     ON DELETE CASCADE,
    permiso_id smallint NOT NULL REFERENCES permiso(id) ON DELETE CASCADE,
    PRIMARY KEY (rol_id, permiso_id)
);


CREATE TABLE usuario (
    id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    correo           text        NOT NULL,
    nombre_usuario   text        NOT NULL,
    clave_hash       text,
    estado           text        NOT NULL DEFAULT 'ACTIVO',
    mfa_habilitado   boolean     NOT NULL DEFAULT false,
    mfa_secreto      text,
    intentos_fallidos smallint   NOT NULL DEFAULT 0,
    bloqueado_hasta  timestamptz,
    ultimo_acceso_en timestamptz,
    creado_en        timestamptz NOT NULL DEFAULT now(),
    actualizado_en   timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_usuario_estado
        CHECK (estado IN ('ACTIVO', 'SUSPENDIDO', 'DESACTIVADO')),
    CONSTRAINT ck_usuario_correo_formato
        CHECK (correo ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
    CONSTRAINT ck_usuario_nombre_usuario_formato
        CHECK (nombre_usuario ~ '^[a-z0-9][a-z0-9_-]{2,29}$'),
    CONSTRAINT ck_usuario_intentos
        CHECK (intentos_fallidos >= 0)
);

CREATE UNIQUE INDEX ux_usuario_correo         ON usuario (lower(correo));
CREATE UNIQUE INDEX ux_usuario_nombre_usuario ON usuario (lower(nombre_usuario));

COMMENT ON COLUMN usuario.clave_hash IS
    'Argon2id. Nulo cuando la cuenta se creo por GitHub y aun no fijo contrasena (ADR-004).';
COMMENT ON COLUMN usuario.mfa_secreto IS
    'Secreto TOTP cifrado a nivel de columna. La clave vive en variable de entorno, nunca en el repositorio.';
COMMENT ON COLUMN usuario.estado IS
    'No existe PENDIENTE_VERIFICACION: la verificacion se resuelve vinculando GitHub (ADR-004).';


CREATE TABLE usuario_rol (
    usuario_id   uuid        NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    rol_id       smallint    NOT NULL REFERENCES rol(id),
    asignado_por uuid        REFERENCES usuario(id),
    asignado_en  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (usuario_id, rol_id)
);


CREATE TABLE identidad_externa (
    id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    usuario_id      uuid        NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    proveedor       text        NOT NULL,
    sujeto_externo  text        NOT NULL,
    usuario_externo text        NOT NULL,
    url_perfil      text,
    vinculado_en    timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_identidad_proveedor CHECK (proveedor IN ('GITHUB')),
    CONSTRAINT ux_identidad_proveedor_sujeto UNIQUE (proveedor, sujeto_externo),
    CONSTRAINT ux_identidad_usuario_proveedor UNIQUE (usuario_id, proveedor)
);

COMMENT ON TABLE identidad_externa IS
    'Tener una fila aqui es lo que marca el perfil como verificado, requisito para publicar (regla R1).';


CREATE TABLE token_refresco (
    id             uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    usuario_id     uuid        NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    token_hash     text        NOT NULL UNIQUE,
    familia        uuid        NOT NULL,
    emitido_en     timestamptz NOT NULL DEFAULT now(),
    expira_en      timestamptz NOT NULL,
    consumido_en   timestamptz,
    revocado_en    timestamptz,
    reemplazado_por uuid       REFERENCES token_refresco(id),
    ip_origen      inet,
    agente_usuario text,

    CONSTRAINT ck_token_vigencia CHECK (expira_en > emitido_en)
);

COMMENT ON COLUMN token_refresco.token_hash IS
    'Solo el hash. El token en claro nunca se almacena ni se registra en logs (lineamientos 6.2).';
COMMENT ON COLUMN token_refresco.familia IS
    'Rotacion con deteccion de reuso: si llega un token ya consumido se revoca la familia completa (ADR-004).';


CREATE TABLE suspension (
    id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    usuario_id   uuid        NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    motivo       text        NOT NULL,
    inicia_en    timestamptz NOT NULL DEFAULT now(),
    termina_en   timestamptz NOT NULL,
    aplicada_por uuid        REFERENCES usuario(id),
    automatica   boolean     NOT NULL DEFAULT false,
    levantada_en timestamptz,

    CONSTRAINT ck_suspension_rango CHECK (termina_en > inicia_en),
    CONSTRAINT ck_suspension_autoria
        CHECK ((automatica AND aplicada_por IS NULL)
            OR (NOT automatica AND aplicada_por IS NOT NULL))
);

COMMENT ON CONSTRAINT ck_suspension_autoria ON suspension IS
    'Una sancion automatica (regla R6) no tiene actor; una manual siempre lo tiene. Evita un usuario "sistema" ficticio.';


-- ============================================================================
-- 2. PERFILES TECNICOS Y GRAFO SOCIAL
-- ============================================================================

CREATE TABLE perfil (
    usuario_id           uuid        PRIMARY KEY REFERENCES usuario(id) ON DELETE CASCADE,
    nombre_completo      text        NOT NULL,
    titular              text,
    biografia            text,
    ubicacion            text,
    url_avatar           text,
    url_sitio_web        text,
    anios_experiencia    smallint,
    disponible_colaborar boolean     NOT NULL DEFAULT false,
    reputacion           integer     NOT NULL DEFAULT 0,
    creado_en            timestamptz NOT NULL DEFAULT now(),
    actualizado_en       timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_perfil_experiencia CHECK (anios_experiencia IS NULL
                                        OR (anios_experiencia BETWEEN 0 AND 70)),
    CONSTRAINT ck_perfil_biografia   CHECK (biografia IS NULL OR length(biografia) <= 2000)
);

COMMENT ON COLUMN perfil.reputacion IS
    'Denormalizacion justificada: se lee en cada elemento del feed y en cada validacion de privilegio. Saldo reconstruible sumando evento_reputacion.';


CREATE TABLE tecnologia (
    id        smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre    text     NOT NULL UNIQUE,
    slug      text     NOT NULL UNIQUE,
    categoria text     NOT NULL,
    aprobada  boolean  NOT NULL DEFAULT false,
    propuesta_por uuid REFERENCES usuario(id),
    creado_en timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_tecnologia_categoria
        CHECK (categoria IN ('LENGUAJE','FRAMEWORK','BASE_DATOS','HERRAMIENTA','CLOUD','OTRA')),
    CONSTRAINT ck_tecnologia_slug CHECK (slug ~ '^[a-z0-9][a-z0-9-]*$')
);

COMMENT ON COLUMN tecnologia.aprobada IS
    'El catalogo lo cura un moderador. Sin curaduria aparecen React, ReactJS y react.js como tres tecnologias.';


CREATE TABLE perfil_tecnologia (
    usuario_id    uuid     NOT NULL REFERENCES perfil(usuario_id) ON DELETE CASCADE,
    tecnologia_id smallint NOT NULL REFERENCES tecnologia(id),
    nivel         text     NOT NULL,
    anios         smallint,
    PRIMARY KEY (usuario_id, tecnologia_id),

    CONSTRAINT ck_perfil_tecnologia_nivel
        CHECK (nivel IN ('BASICO','INTERMEDIO','AVANZADO','EXPERTO')),
    CONSTRAINT ck_perfil_tecnologia_anios
        CHECK (anios IS NULL OR (anios BETWEEN 0 AND 70))
);


CREATE TABLE seguimiento (
    seguidor_id uuid        NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    seguido_id  uuid        NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    creado_en   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (seguidor_id, seguido_id),

    CONSTRAINT ck_seguimiento_no_reflexivo CHECK (seguidor_id <> seguido_id)
);

COMMENT ON TABLE seguimiento IS
    'Relacion reflexiva no simetrica sobre usuario. Seguir no implica ser seguido.';


-- ============================================================================
-- 3. CONTENIDO: supertipo publicacion con especializacion proyecto / discusion
-- ============================================================================

CREATE TABLE publicacion (
    id                    uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    autor_id              uuid        NOT NULL REFERENCES usuario(id),
    tipo                  text        NOT NULL,
    titulo                text        NOT NULL,
    contenido             text        NOT NULL,
    estado                text        NOT NULL DEFAULT 'BORRADOR',
    contador_comentarios  integer     NOT NULL DEFAULT 0,
    contador_reacciones   integer     NOT NULL DEFAULT 0,
    version               integer     NOT NULL DEFAULT 0,
    publicado_en          timestamptz,
    creado_en             timestamptz NOT NULL DEFAULT now(),
    actualizado_en        timestamptz NOT NULL DEFAULT now(),

    -- El cast explicito a regconfig fija la resolucion a to_tsvector(regconfig, text),
    -- que es IMMUTABLE y por tanto admisible en una columna generada.
    busqueda_tsv tsvector GENERATED ALWAYS AS (
        to_tsvector('spanish'::regconfig, coalesce(titulo, '') || ' ' || coalesce(contenido, ''))
    ) STORED,

    CONSTRAINT ck_publicacion_tipo   CHECK (tipo IN ('PROYECTO','DISCUSION')),
    CONSTRAINT ck_publicacion_estado
        CHECK (estado IN ('BORRADOR','PUBLICADO','EN_REVISION','OCULTO','ARCHIVADO')),
    CONSTRAINT ck_publicacion_titulo  CHECK (length(btrim(titulo)) BETWEEN 5 AND 200),
    CONSTRAINT ck_publicacion_contenido CHECK (length(btrim(contenido)) >= 20),
    CONSTRAINT ck_publicacion_contadores
        CHECK (contador_comentarios >= 0 AND contador_reacciones >= 0),
    CONSTRAINT ck_publicacion_publicado_en
        CHECK ((estado = 'BORRADOR' AND publicado_en IS NULL)
            OR (estado <> 'BORRADOR' AND publicado_en IS NOT NULL))
);

COMMENT ON TABLE publicacion IS
    'Supertipo de PROYECTO y DISCUSION. Permite que comentario, reaccion y reporte usen una clave foranea real en lugar de una referencia polimorfica.';
COMMENT ON COLUMN publicacion.busqueda_tsv IS
    'Columna generada y persistida: el vector no se calcula en tiempo de consulta. Indice GIN mas abajo.';
COMMENT ON COLUMN publicacion.version IS
    'Bloqueo optimista de JPA. Produce el 409 CONFLICTO_CONCURRENCIA del ADR-005.';
COMMENT ON CONSTRAINT ck_publicacion_publicado_en ON publicacion IS
    'Un borrador nunca tiene fecha de publicacion; cualquier otro estado siempre la tiene.';


CREATE TABLE publicacion_proyecto (
    publicacion_id       uuid     PRIMARY KEY REFERENCES publicacion(id) ON DELETE CASCADE,
    resumen              text     NOT NULL,
    licencia             text,
    estado_proyecto      text     NOT NULL DEFAULT 'IDEA',
    busca_colaboradores  boolean  NOT NULL DEFAULT false,
    max_colaboradores    smallint NOT NULL DEFAULT 5,
    url_demo             text,

    CONSTRAINT ck_proyecto_estado
        CHECK (estado_proyecto IN ('IDEA','EN_DESARROLLO','ESTABLE','PAUSADO')),
    CONSTRAINT ck_proyecto_max_colaboradores
        CHECK (max_colaboradores BETWEEN 1 AND 50)
);


CREATE TABLE publicacion_discusion (
    publicacion_id        uuid    PRIMARY KEY REFERENCES publicacion(id) ON DELETE CASCADE,
    categoria             text    NOT NULL,
    resuelta              boolean NOT NULL DEFAULT false,
    comentario_aceptado_id uuid,   -- FK anadida mas abajo: dependencia circular con comentario

    CONSTRAINT ck_discusion_categoria
        CHECK (categoria IN ('PREGUNTA','DEBATE','ANUNCIO','RECURSO')),
    CONSTRAINT ck_discusion_resuelta_coherente
        CHECK ((resuelta AND comentario_aceptado_id IS NOT NULL)
            OR (NOT resuelta AND comentario_aceptado_id IS NULL))
);


CREATE TABLE repositorio (
    id                      uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    publicacion_proyecto_id uuid        NOT NULL REFERENCES publicacion_proyecto(publicacion_id) ON DELETE CASCADE,
    proveedor               text        NOT NULL DEFAULT 'GITHUB',
    url                     text        NOT NULL UNIQUE,
    rama_principal          text        NOT NULL DEFAULT 'main',
    estrellas               integer     NOT NULL DEFAULT 0,
    ultima_sincronizacion   timestamptz,

    CONSTRAINT ck_repositorio_proveedor CHECK (proveedor IN ('GITHUB','GITLAB','OTRO')),
    CONSTRAINT ck_repositorio_url       CHECK (url ~* '^https://'),
    CONSTRAINT ck_repositorio_estrellas  CHECK (estrellas >= 0)
);


CREATE TABLE publicacion_tecnologia (
    publicacion_id uuid     NOT NULL REFERENCES publicacion(id) ON DELETE CASCADE,
    tecnologia_id  smallint NOT NULL REFERENCES tecnologia(id),
    PRIMARY KEY (publicacion_id, tecnologia_id)
);

COMMENT ON TABLE publicacion_tecnologia IS
    'Regla R1: entre 1 y 5 tecnologias por publicacion. La cota superior se valida en el dominio porque una restriccion declarativa no puede contar filas de otra tabla.';


CREATE TABLE historial_estado_publicacion (
    id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    publicacion_id  uuid        NOT NULL REFERENCES publicacion(id) ON DELETE CASCADE,
    estado_anterior text,
    estado_nuevo    text        NOT NULL,
    actor_id        uuid        REFERENCES usuario(id),
    motivo          text,
    creado_en       timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_historial_estados_distintos
        CHECK (estado_anterior IS NULL OR estado_anterior <> estado_nuevo)
);

COMMENT ON TABLE historial_estado_publicacion IS
    'Regla R7: toda transicion escribe aqui en la misma transaccion que el cambio de estado. Si no se puede escribir el historial, la transicion no ocurre.';


CREATE TABLE colaboracion (
    id                      uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    publicacion_proyecto_id uuid        NOT NULL REFERENCES publicacion_proyecto(publicacion_id) ON DELETE CASCADE,
    usuario_id              uuid        NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    estado                  text        NOT NULL DEFAULT 'SOLICITADA',
    rol_colaborador         text,
    mensaje_solicitud       text,
    resuelto_por            uuid        REFERENCES usuario(id),
    solicitado_en           timestamptz NOT NULL DEFAULT now(),
    resuelto_en             timestamptz,
    retirado_en             timestamptz,

    CONSTRAINT ck_colaboracion_estado
        CHECK (estado IN ('SOLICITADA','ACEPTADA','RECHAZADA','ACTIVA','RETIRADA')),
    CONSTRAINT ux_colaboracion_proyecto_usuario
        UNIQUE (publicacion_proyecto_id, usuario_id)
);

COMMENT ON CONSTRAINT ux_colaboracion_proyecto_usuario ON colaboracion IS
    'El reingreso tras retiro transiciona la fila existente, no crea una nueva. Es lo que sostiene la regla C3.';


-- ============================================================================
-- 4. INTERACCION
-- ============================================================================

CREATE TABLE comentario (
    id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    publicacion_id      uuid        NOT NULL REFERENCES publicacion(id) ON DELETE CASCADE,
    autor_id            uuid        NOT NULL REFERENCES usuario(id),
    comentario_padre_id uuid        REFERENCES comentario(id) ON DELETE CASCADE,
    contenido           text        NOT NULL,
    estado              text        NOT NULL DEFAULT 'PUBLICADO',
    profundidad         smallint    NOT NULL DEFAULT 0,
    contador_reacciones integer     NOT NULL DEFAULT 0,
    editado             boolean     NOT NULL DEFAULT false,
    creado_en           timestamptz NOT NULL DEFAULT now(),
    actualizado_en      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_comentario_estado      CHECK (estado IN ('PUBLICADO','OCULTO','ELIMINADO')),
    CONSTRAINT ck_comentario_contenido   CHECK (length(btrim(contenido)) BETWEEN 1 AND 5000),
    CONSTRAINT ck_comentario_profundidad CHECK (profundidad BETWEEN 0 AND 5),
    CONSTRAINT ck_comentario_raiz
        CHECK ((comentario_padre_id IS NULL AND profundidad = 0)
            OR (comentario_padre_id IS NOT NULL AND profundidad > 0))
);

COMMENT ON CONSTRAINT ck_comentario_profundidad ON comentario IS
    'La cota no es estetica: sin ella el CTE recursivo del hilo (P02) no tiene techo de costo.';


ALTER TABLE publicacion_discusion
    ADD CONSTRAINT fk_discusion_comentario_aceptado
    FOREIGN KEY (comentario_aceptado_id) REFERENCES comentario(id) ON DELETE SET NULL;


CREATE TABLE reaccion_publicacion (
    usuario_id     uuid        NOT NULL REFERENCES usuario(id)     ON DELETE CASCADE,
    publicacion_id uuid        NOT NULL REFERENCES publicacion(id) ON DELETE CASCADE,
    tipo           text        NOT NULL,
    creado_en      timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (usuario_id, publicacion_id),

    CONSTRAINT ck_reaccion_pub_tipo CHECK (tipo IN ('ME_GUSTA','UTIL','INNOVADOR'))
);

COMMENT ON TABLE reaccion_publicacion IS
    'La clave primaria compuesta impone una sola reaccion por usuario y publicacion. Cambiar de tipo es UPDATE, no una segunda fila.';


CREATE TABLE reaccion_comentario (
    usuario_id    uuid        NOT NULL REFERENCES usuario(id)    ON DELETE CASCADE,
    comentario_id uuid        NOT NULL REFERENCES comentario(id) ON DELETE CASCADE,
    tipo          text        NOT NULL,
    creado_en     timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (usuario_id, comentario_id),

    CONSTRAINT ck_reaccion_com_tipo CHECK (tipo IN ('ME_GUSTA','UTIL','INNOVADOR'))
);


CREATE TABLE evento_reputacion (
    id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    usuario_id      uuid        NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    tipo_evento     text        NOT NULL,
    puntos          smallint    NOT NULL,
    referencia_tipo text,
    referencia_id   uuid,
    creado_en       timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_evento_reputacion_tipo CHECK (tipo_evento IN (
        'REACCION_EN_PUBLICACION',
        'REACCION_EN_COMENTARIO',
        'COMENTARIO_ACEPTADO',
        'PROYECTO_CON_REPOSITORIO',
        'PUBLICACION_OCULTADA',
        'SUSPENSION_APLICADA',
        'AJUSTE_ADMINISTRATIVO'
    )),
    CONSTRAINT ck_evento_reputacion_puntos CHECK (puntos <> 0)
);

COMMENT ON TABLE evento_reputacion IS
    'Libro mayor append-only. Nunca se actualiza ni se borra. perfil.reputacion es su saldo y siempre es reconstruible sumando esta tabla.';


-- ============================================================================
-- 5. MENSAJERIA PRIVADA
-- ============================================================================

CREATE TABLE conversacion (
    id                uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    creada_por        uuid        NOT NULL REFERENCES usuario(id),
    clave_directa     text,
    ultimo_mensaje_en timestamptz,
    creada_en         timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_conversacion_clave_directa
        CHECK (clave_directa IS NULL OR clave_directa ~ '^[0-9a-f-]{36}:[0-9a-f-]{36}$')
);

COMMENT ON COLUMN conversacion.clave_directa IS
    'Los dos uuid de los participantes ordenados como "menor:mayor". Con el indice unico parcial impide conversaciones directas duplicadas, sin renunciar a soportar grupos despues (donde queda nula).';


CREATE TABLE participante_conversacion (
    conversacion_id uuid        NOT NULL REFERENCES conversacion(id) ON DELETE CASCADE,
    usuario_id      uuid        NOT NULL REFERENCES usuario(id)      ON DELETE CASCADE,
    ultimo_leido_en timestamptz,
    silenciada      boolean     NOT NULL DEFAULT false,
    abandonada_en   timestamptz,
    unido_en        timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (conversacion_id, usuario_id)
);

COMMENT ON COLUMN participante_conversacion.ultimo_leido_en IS
    'Evita una tabla de estado de lectura por mensaje y por participante, que multiplicaria el volumen de la tabla que mas crece para responder la misma pregunta (P05).';


CREATE TABLE mensaje (
    id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    conversacion_id uuid        NOT NULL REFERENCES conversacion(id) ON DELETE CASCADE,
    remitente_id    uuid        NOT NULL REFERENCES usuario(id),
    contenido       text        NOT NULL,
    enviado_en      timestamptz NOT NULL DEFAULT now(),
    editado_en      timestamptz,
    eliminado_en    timestamptz,

    CONSTRAINT ck_mensaje_contenido CHECK (length(btrim(contenido)) BETWEEN 1 AND 4000)
);

COMMENT ON COLUMN mensaje.eliminado_en IS
    'Borrado logico: el fisico romperia la continuidad de la conversacion y eliminaria evidencia necesaria para moderar acoso.';


-- ============================================================================
-- 6. MODERACION
-- ============================================================================

CREATE TABLE reporte_moderacion (
    id             uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    reportante_id  uuid        NOT NULL REFERENCES usuario(id),
    publicacion_id uuid        REFERENCES publicacion(id) ON DELETE CASCADE,
    comentario_id  uuid        REFERENCES comentario(id)  ON DELETE CASCADE,
    motivo         text        NOT NULL,
    detalle        text,
    estado         text        NOT NULL DEFAULT 'ABIERTO',
    moderador_id   uuid        REFERENCES usuario(id),
    resolucion     text,
    es_apelacion   boolean     NOT NULL DEFAULT false,
    creado_en      timestamptz NOT NULL DEFAULT now(),
    resuelto_en    timestamptz,

    CONSTRAINT ck_reporte_objetivo_exclusivo
        CHECK ((publicacion_id IS NULL) <> (comentario_id IS NULL)),
    CONSTRAINT ck_reporte_motivo
        CHECK (motivo IN ('SPAM','ACOSO','CONTENIDO_INAPROPIADO','PLAGIO','OTRA')),
    CONSTRAINT ck_reporte_estado
        CHECK (estado IN ('ABIERTO','EN_REVISION','RESUELTO_ACEPTADO','RESUELTO_DESESTIMADO')),
    CONSTRAINT ck_reporte_no_autorreporte
        CHECK (reportante_id <> coalesce(moderador_id, '00000000-0000-0000-0000-000000000000'::uuid)),
    CONSTRAINT ck_reporte_resolucion_coherente
        CHECK ((estado LIKE 'RESUELTO%'
                    AND moderador_id IS NOT NULL
                    AND resolucion IS NOT NULL
                    AND length(btrim(resolucion)) >= 20
                    AND resuelto_en IS NOT NULL)
            OR (estado NOT LIKE 'RESUELTO%'))
);

COMMENT ON CONSTRAINT ck_reporte_objetivo_exclusivo ON reporte_moderacion IS
    'Disyuncion exclusiva sin renunciar a claves foraneas reales: exactamente una publicacion o un comentario, nunca ambos ni ninguno.';
COMMENT ON CONSTRAINT ck_reporte_no_autorreporte ON reporte_moderacion IS
    'Regla R3, parte declarativa: el moderador que resuelve no puede ser el reportante. Que tampoco sea el autor se valida en el dominio, porque la autoria vive en otra tabla.';
COMMENT ON CONSTRAINT ck_reporte_resolucion_coherente ON reporte_moderacion IS
    'Regla R3: no hay resolucion silenciosa. Motivo escrito de 20 caracteres minimo, moderador y fecha.';


-- ============================================================================
-- 7. AUDITORIA Y ANALITICA
-- ============================================================================

CREATE TABLE auditoria (
    id             bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabla          text        NOT NULL,
    operacion      text        NOT NULL,
    registro_id    text        NOT NULL,
    actor_id       uuid,
    datos_antes    jsonb,
    datos_despues  jsonb,
    trace_id       text,
    ip             inet,
    creado_en      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_auditoria_operacion CHECK (operacion IN ('INSERT','UPDATE','DELETE'))
);

COMMENT ON TABLE auditoria IS
    'Alimentada por triggers (V3), no por la aplicacion: asi captura tambien los cambios hechos por consola o migracion (lineamientos 5.4).';
COMMENT ON COLUMN auditoria.actor_id IS
    'Sin clave foranea a proposito: el registro de auditoria debe sobrevivir al borrado del usuario que lo genero.';
COMMENT ON COLUMN auditoria.registro_id IS
    'text y no uuid: audita tambien tablas cuya clave primaria no es uuid (rol, permiso, metricas_diarias).';
COMMENT ON COLUMN auditoria.trace_id IS
    'Une un cambio en la base con la linea de log y con la respuesta que recibio el cliente (ADR-005).';


CREATE TABLE metricas_diarias (
    fecha                   date        PRIMARY KEY,
    usuarios_nuevos         integer     NOT NULL DEFAULT 0,
    usuarios_activos        integer     NOT NULL DEFAULT 0,
    publicaciones_nuevas    integer     NOT NULL DEFAULT 0,
    proyectos_nuevos        integer     NOT NULL DEFAULT 0,
    discusiones_nuevas      integer     NOT NULL DEFAULT 0,
    comentarios_nuevos      integer     NOT NULL DEFAULT 0,
    mensajes_enviados       integer     NOT NULL DEFAULT 0,
    colaboraciones_aceptadas integer    NOT NULL DEFAULT 0,
    reportes_abiertos       integer     NOT NULL DEFAULT 0,
    calculado_en            timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE metricas_diarias IS
    'Tabla de hechos preagregada. Separa el camino de lectura analitico del transaccional: sin ella, los reportes de 90 dias (P13-P15) agregarian en vivo sobre publicacion, comentario y mensaje.';


-- ============================================================================
-- 8. INDICES
--    Cada uno responde a una pregunta de docs/bd/01-consultas-clave.md.
--    La justificacion completa esta en docs/bd/04-indices.md.
-- ============================================================================

-- P01 feed: indice PARCIAL, el feed solo mira publicaciones en estado PUBLICADO
CREATE INDEX ix_publicacion_feed
    ON publicacion (publicado_en DESC, id DESC)
    WHERE estado = 'PUBLICADO';

-- P04 busqueda por texto completo
CREATE INDEX ix_publicacion_busqueda
    ON publicacion USING GIN (busqueda_tsv);

-- P01, P10 publicaciones por autor y estado
CREATE INDEX ix_publicacion_autor_estado
    ON publicacion (autor_id, estado, creado_en DESC);

-- P01, P03 resolucion de etiquetas en sentido tecnologia -> publicacion
CREATE INDEX ix_publicacion_tecnologia_inverso
    ON publicacion_tecnologia (tecnologia_id, publicacion_id);

-- P03 proyectos que buscan colaboradores
CREATE INDEX ix_proyecto_busca_colaboradores
    ON publicacion_proyecto (publicacion_id)
    WHERE busca_colaboradores = true;

-- P02 hilo de comentarios: ancla del CTE recursivo
CREATE INDEX ix_comentario_publicacion_padre
    ON comentario (publicacion_id, comentario_padre_id, creado_en);

-- P05 bandeja: ultimo mensaje por conversacion y conteo de no leidos
CREATE INDEX ix_mensaje_conversacion
    ON mensaje (conversacion_id, enviado_en DESC);

-- P05 conversaciones de un usuario
CREATE INDEX ix_participante_usuario
    ON participante_conversacion (usuario_id, conversacion_id)
    WHERE abandonada_en IS NULL;

-- P05 unicidad de la conversacion directa entre dos usuarios
CREATE UNIQUE INDEX ux_conversacion_directa
    ON conversacion (clave_directa)
    WHERE clave_directa IS NOT NULL;

-- P06 libro mayor de reputacion por usuario
CREATE INDEX ix_evento_reputacion_usuario
    ON evento_reputacion (usuario_id, creado_en DESC);

-- P07 seguidores (el sentido inverso ya lo cubre la clave primaria compuesta)
CREATE INDEX ix_seguimiento_seguido
    ON seguimiento (seguido_id, seguidor_id);

-- P08 solicitudes de colaboracion de un usuario
CREATE INDEX ix_colaboracion_usuario
    ON colaboracion (usuario_id, estado);

-- P09 cola de moderacion: parcial, solo lo que esta pendiente
CREATE INDEX ix_reporte_pendiente
    ON reporte_moderacion (creado_en)
    WHERE estado IN ('ABIERTO','EN_REVISION');

-- P11 historial de una publicacion
CREATE INDEX ix_historial_publicacion
    ON historial_estado_publicacion (publicacion_id, creado_en DESC);

-- P12 suspensiones vigentes
CREATE INDEX ix_suspension_vigente
    ON suspension (usuario_id, termina_en DESC)
    WHERE levantada_en IS NULL;

-- P16 busqueda en auditoria
CREATE INDEX ix_auditoria_registro ON auditoria (tabla, registro_id, creado_en DESC);
CREATE INDEX ix_auditoria_trace    ON auditoria (trace_id) WHERE trace_id IS NOT NULL;

-- P17 catalogo pendiente de aprobacion
CREATE INDEX ix_tecnologia_pendiente
    ON tecnologia (creado_en)
    WHERE aprobada = false;

-- Identidad: limpieza y revocacion de tokens
CREATE INDEX ix_token_familia
    ON token_refresco (familia)
    WHERE revocado_en IS NULL;
CREATE INDEX ix_token_usuario_vigente
    ON token_refresco (usuario_id, expira_en)
    WHERE revocado_en IS NULL AND consumido_en IS NULL;


-- ============================================================================
-- 9. TRIGGERS DE MARCA DE ACTUALIZACION
-- ============================================================================

CREATE TRIGGER tg_usuario_actualizado    BEFORE UPDATE ON usuario
    FOR EACH ROW EXECUTE FUNCTION fn_set_actualizado_en();
CREATE TRIGGER tg_perfil_actualizado     BEFORE UPDATE ON perfil
    FOR EACH ROW EXECUTE FUNCTION fn_set_actualizado_en();
CREATE TRIGGER tg_publicacion_actualizado BEFORE UPDATE ON publicacion
    FOR EACH ROW EXECUTE FUNCTION fn_set_actualizado_en();
CREATE TRIGGER tg_comentario_actualizado BEFORE UPDATE ON comentario
    FOR EACH ROW EXECUTE FUNCTION fn_set_actualizado_en();


-- ============================================================================
-- 10. DATOS DE REFERENCIA
--     Roles, permisos y catalogo inicial de tecnologias. No son datos de
--     prueba: el sistema no arranca sin ellos.
-- ============================================================================

INSERT INTO rol (codigo, descripcion, exige_mfa) VALUES
    ('VISITANTE',     'Acceso de solo lectura al contenido publico',            false),
    ('DESARROLLADOR', 'Miembro de la comunidad con capacidades sociales plenas', false),
    ('MODERADOR',     'Resuelve reportes, oculta contenido y aplica sanciones',  true),
    ('ADMIN',         'Gestiona roles, catalogo y consulta reportes y auditoria', true);

INSERT INTO permiso (codigo, descripcion) VALUES
    ('perfil:leer',               'Consultar perfiles publicos'),
    ('perfil:editar',             'Editar el perfil propio'),
    ('publicacion:crear',         'Crear borradores de proyecto o discusion'),
    ('publicacion:editar',        'Editar publicaciones propias'),
    ('publicacion:publicar',      'Publicar un borrador propio'),
    ('publicacion:archivar',      'Archivar una publicacion propia'),
    ('publicacion:moderar',       'Ocultar o restaurar publicaciones ajenas'),
    ('comentario:crear',          'Comentar publicaciones'),
    ('comentario:editar',         'Editar comentarios propios'),
    ('reaccion:crear',            'Reaccionar a publicaciones y comentarios'),
    ('reporte:crear',             'Reportar contenido'),
    ('reporte:resolver',          'Resolver reportes de moderacion'),
    ('mensaje:enviar',            'Enviar mensajes privados'),
    ('colaboracion:solicitar',    'Solicitar colaborar en un proyecto'),
    ('colaboracion:resolver',     'Aceptar o rechazar solicitudes en proyectos propios'),
    ('usuario:suspender',         'Suspender cuentas'),
    ('usuario:gestionar-roles',   'Asignar y retirar roles'),
    ('tecnologia:aprobar',        'Aprobar tecnologias propuestas por la comunidad'),
    ('reporte-comunidad:consultar','Consultar reportes de actividad y crecimiento'),
    ('auditoria:consultar',       'Consultar el registro de auditoria');

INSERT INTO rol_permiso (rol_id, permiso_id)
SELECT r.id, p.id
FROM (VALUES
    ('VISITANTE',     'perfil:leer'),

    ('DESARROLLADOR', 'perfil:leer'),
    ('DESARROLLADOR', 'perfil:editar'),
    ('DESARROLLADOR', 'publicacion:crear'),
    ('DESARROLLADOR', 'publicacion:editar'),
    ('DESARROLLADOR', 'publicacion:publicar'),
    ('DESARROLLADOR', 'publicacion:archivar'),
    ('DESARROLLADOR', 'comentario:crear'),
    ('DESARROLLADOR', 'comentario:editar'),
    ('DESARROLLADOR', 'reaccion:crear'),
    ('DESARROLLADOR', 'reporte:crear'),
    ('DESARROLLADOR', 'mensaje:enviar'),
    ('DESARROLLADOR', 'colaboracion:solicitar'),
    ('DESARROLLADOR', 'colaboracion:resolver'),

    ('MODERADOR',     'perfil:leer'),
    ('MODERADOR',     'perfil:editar'),
    ('MODERADOR',     'publicacion:crear'),
    ('MODERADOR',     'publicacion:editar'),
    ('MODERADOR',     'publicacion:publicar'),
    ('MODERADOR',     'publicacion:archivar'),
    ('MODERADOR',     'publicacion:moderar'),
    ('MODERADOR',     'comentario:crear'),
    ('MODERADOR',     'comentario:editar'),
    ('MODERADOR',     'reaccion:crear'),
    ('MODERADOR',     'reporte:crear'),
    ('MODERADOR',     'reporte:resolver'),
    ('MODERADOR',     'mensaje:enviar'),
    ('MODERADOR',     'colaboracion:solicitar'),
    ('MODERADOR',     'colaboracion:resolver'),
    ('MODERADOR',     'usuario:suspender'),
    ('MODERADOR',     'tecnologia:aprobar'),

    ('ADMIN',         'perfil:leer'),
    ('ADMIN',         'perfil:editar'),
    ('ADMIN',         'publicacion:moderar'),
    ('ADMIN',         'reporte:resolver'),
    ('ADMIN',         'usuario:suspender'),
    ('ADMIN',         'usuario:gestionar-roles'),
    ('ADMIN',         'tecnologia:aprobar'),
    ('ADMIN',         'reporte-comunidad:consultar'),
    ('ADMIN',         'auditoria:consultar')
) AS m(rol_codigo, permiso_codigo)
JOIN rol     r ON r.codigo = m.rol_codigo
JOIN permiso p ON p.codigo = m.permiso_codigo;

INSERT INTO tecnologia (nombre, slug, categoria, aprobada) VALUES
    ('Java',       'java',       'LENGUAJE',    true),
    ('TypeScript', 'typescript', 'LENGUAJE',    true),
    ('Python',     'python',     'LENGUAJE',    true),
    ('Go',         'go',         'LENGUAJE',    true),
    ('Rust',       'rust',       'LENGUAJE',    true),
    ('Kotlin',     'kotlin',     'LENGUAJE',    true),
    ('Spring Boot','spring-boot','FRAMEWORK',   true),
    ('React',      'react',      'FRAMEWORK',   true),
    ('Next.js',    'nextjs',     'FRAMEWORK',   true),
    ('Angular',    'angular',    'FRAMEWORK',   true),
    ('PostgreSQL', 'postgresql', 'BASE_DATOS',  true),
    ('MongoDB',    'mongodb',    'BASE_DATOS',  true),
    ('Redis',      'redis',      'BASE_DATOS',  true),
    ('Docker',     'docker',     'HERRAMIENTA', true),
    ('Kubernetes', 'kubernetes', 'HERRAMIENTA', true),
    ('Git',        'git',        'HERRAMIENTA', true),
    ('AWS',        'aws',        'CLOUD',       true),
    ('Azure',      'azure',      'CLOUD',       true),
    ('Supabase',   'supabase',   'CLOUD',       true),
    ('Render',     'render',     'CLOUD',       true);